name: proxi_pyme
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  jwt_decoder: ^2.0.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1
  google_places_flutter: ^2.0.6
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  flutter_spinkit: "^5.1.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - .env
      - assets/
      - assets/images/
      - assets/icons/
      